# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a379571a74147a9b22012421d09fff0b6efeca0bdcd46eb984eb9f56a7b1627d1d78075b6e8c2601904578ba3df8a4ebb11b4c5426e090d162c81b52595781d9

test:
  secret_key_base: f641f6bc1d0c87f90655075002cb2577de5b723edb9b9b15f7aed98d02841a5e502b23085f501a362005469225a5f16f0c7816a60ded76187c7dff73ba64a959

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
